// Cross-service message contract test (ADR-011 §6) — the Go half.
//
// The fixtures under contracts/fixtures/ are generated by contracts/test_message_contract.py
// from the models the API actually publishes through, and that test fails if they drift.
// So what runs here is a real API payload through the real worker parser.
//
// This half is the one that matters most. BUG-005's silent variant existed only on the
// Python→Go boundary: encoding/json turns a JSON null into "" and reports no error, so
// a batch dispatch that crashed the Python workers made this one write every item of
// every tenant to a single shared object instead. No amount of Python-side testing
// reaches that.
package worker

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

const fixtureDir = "../../../contracts/fixtures"

// lanes maps each dispatcher's fixture to whether that lane carries a run_id.
// The crawl lane does not: a crawl page creates no job_runs row (ADR-011 §2).
var lanes = map[string]bool{
	"job_http":       true,
	"job_playwright": true,
	"scheduled":      true,
	"batch":          true,
	"crawl":          false,
}

func readFixture(t *testing.T, lane string) []byte {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(fixtureDir, lane+".json"))
	if err != nil {
		t.Fatalf("reading fixture %s: %v (regenerate with UPDATE_CONTRACT_FIXTURES=1)", lane, err)
	}
	return data
}

func TestContract_EveryDispatcherPayloadParsesAndValidates(t *testing.T) {
	for lane := range lanes {
		t.Run(lane, func(t *testing.T) {
			var job ScrapeMessage
			if err := json.Unmarshal(readFixture(t, lane), &job); err != nil {
				t.Fatalf("unmarshal: %v", err)
			}
			if err := validateMessage(&job); err != nil {
				t.Fatalf("validateMessage rejected a real dispatch payload: %v", err)
			}
			if job.SchemaVersion != supportedSchemaVersion {
				t.Errorf("schema_version: got %d, want %d", job.SchemaVersion, supportedSchemaVersion)
			}
			if job.URL == "" || job.OutputFormat == "" {
				t.Errorf("url/output_format must survive the wire: %+v", job)
			}
		})
	}
}

func TestContract_ArtifactIDSurvivesTheWireIntact(t *testing.T) {
	// The worker builds every object path from this string verbatim, so a value that
	// changes in transit silently relocates the artifact.
	for lane := range lanes {
		t.Run(lane, func(t *testing.T) {
			raw := readFixture(t, lane)

			var asMap map[string]any
			if err := json.Unmarshal(raw, &asMap); err != nil {
				t.Fatalf("unmarshal to map: %v", err)
			}
			want, _ := asMap["artifact_id"].(string)
			if want == "" {
				t.Fatalf("fixture has no artifact_id: %s", raw)
			}

			var job ScrapeMessage
			if err := json.Unmarshal(raw, &job); err != nil {
				t.Fatalf("unmarshal: %v", err)
			}
			if job.ArtifactID != want {
				t.Errorf("artifact_id: got %q, want %q", job.ArtifactID, want)
			}
		})
	}
}

func TestContract_RunIDPresenceMatchesTheLane(t *testing.T) {
	for lane, hasRun := range lanes {
		t.Run(lane, func(t *testing.T) {
			var job ScrapeMessage
			if err := json.Unmarshal(readFixture(t, lane), &job); err != nil {
				t.Fatalf("unmarshal: %v", err)
			}
			switch {
			case hasRun && job.RunID == nil:
				t.Error("run_id must be present on a lane that creates a job_runs row")
			case hasRun && *job.RunID == "":
				t.Error("run_id present but empty — the Path B shape")
			case !hasRun && job.RunID != nil:
				t.Errorf("crawl lane must omit run_id entirely, got %q", *job.RunID)
			}
		})
	}
}

func TestContract_NoLanePutsJobIDOnTheWire(t *testing.T) {
	for lane := range lanes {
		t.Run(lane, func(t *testing.T) {
			var asMap map[string]any
			if err := json.Unmarshal(readFixture(t, lane), &asMap); err != nil {
				t.Fatalf("unmarshal to map: %v", err)
			}
			if _, present := asMap["job_id"]; present {
				t.Error("job_id has left the wire (ADR-011 §2)")
			}
		})
	}
}

// ---------------------------------------------------------------------------
// The BUG-005 Path B regression itself
// ---------------------------------------------------------------------------

func TestContract_LegacyBatchPayloadIsRejectedNotDefaulted(t *testing.T) {
	// The exact bytes routers/batch.py used to publish. Unmarshalling still succeeds —
	// that is the point, and it is why this needs an explicit check rather than an
	// error return. What must not happen is the worker proceeding.
	legacy := []byte(`{
		"schema_version": 2,
		"job_id": null,
		"run_id": "3f8b7a12-0c44-4e7a-9a1e-1b2c3d4e5f60",
		"url": "https://example.com/a",
		"output_format": "html",
		"engine": "http",
		"credentials": null,
		"options": {"respect_robots": false},
		"crawl_context": null
	}`)

	var job ScrapeMessage
	if err := json.Unmarshal(legacy, &job); err != nil {
		t.Fatalf("expected encoding/json to accept this payload, got: %v", err)
	}
	if err := validateMessage(&job); err == nil {
		t.Fatal("a v2 batch payload must be rejected; accepting it is BUG-005 Path B")
	}
}

func TestContract_EmptyArtifactIDIsRejected(t *testing.T) {
	// A JSON null in a string field unmarshals to "" with no error. That single
	// behaviour is what turned a loud crash on the Python workers into cross-tenant
	// corruption here, so it is asserted directly rather than inferred.
	var job ScrapeMessage
	if err := json.Unmarshal([]byte(`{"schema_version":3,"artifact_id":null,"url":"u","output_format":"html"}`), &job); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	if job.ArtifactID != "" {
		t.Fatalf("expected null to default to \"\", got %q", job.ArtifactID)
	}
	if err := validateMessage(&job); err == nil {
		t.Fatal("an empty artifact_id must be rejected, never defaulted (ADR-011 §5)")
	}
}

func TestContract_PresentButEmptyRunIDIsRejected(t *testing.T) {
	// Absent is legitimate; empty is a producer bug. A plain string field could not
	// tell them apart, which is why RunID is a pointer.
	var job ScrapeMessage
	if err := json.Unmarshal([]byte(`{"schema_version":3,"artifact_id":"a","run_id":"","url":"u","output_format":"html"}`), &job); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	if err := validateMessage(&job); err == nil {
		t.Fatal("a present-but-empty run_id must be rejected")
	}

	var crawl ScrapeMessage
	if err := json.Unmarshal([]byte(`{"schema_version":3,"artifact_id":"a","url":"u","output_format":"html"}`), &crawl); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	if err := validateMessage(&crawl); err != nil {
		t.Fatalf("an absent run_id is valid on the crawl lane, got: %v", err)
	}
}
