// Cross-service activity contract test, Go half. The scrape_input_*.json fixtures are generated by
// contracts/test_activity_contract.py from the API's models; go_scrape_output.json is generated here
// and parsed by that test with the API's model. Regenerate it with
//
//	UPDATE_CONTRACT_FIXTURES=1 go test -count=1 ./internal/activity/
//
// -count=1 is required: a cached pass skips the write.
package activity

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

const fixtureDir = "../../../contracts/fixtures/activity"

func readFixture(t *testing.T, name string) []byte {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(fixtureDir, name+".json"))
	if err != nil {
		t.Fatalf("reading fixture %s: %v (regenerate with UPDATE_CONTRACT_FIXTURES=1)", name, err)
	}
	return data
}

func TestContract_APIScrapeInputsParseAndValidate(t *testing.T) {
	for _, name := range []string{"scrape_input_http", "scrape_input_minimal"} {
		t.Run(name, func(t *testing.T) {
			raw := readFixture(t, name)

			var asMap map[string]any
			if err := json.Unmarshal(raw, &asMap); err != nil {
				t.Fatalf("unmarshal to map: %v", err)
			}

			var in ScrapeInput
			if err := json.Unmarshal(raw, &in); err != nil {
				t.Fatalf("unmarshal: %v", err)
			}
			if err := in.Validate(); err != nil {
				t.Fatalf("Validate rejected a real API payload: %v", err)
			}
			if in.ArtifactID != asMap["artifact_id"] || in.URL != asMap["url"] || in.OutputFormat != asMap["output_format"] {
				t.Errorf("fields changed in transit: %+v vs %v", in, asMap)
			}
		})
	}
}

func TestContract_NestedFieldsSurvive(t *testing.T) {
	var in ScrapeInput
	if err := json.Unmarshal(readFixture(t, "scrape_input_http"), &in); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	if in.Credentials == nil || in.Credentials.EncryptedProxyURL != "gAAAAAB_proxy" {
		t.Errorf("credentials: %+v", in.Credentials)
	}
	if in.Options == nil || !in.Options.RespectRobots {
		t.Errorf("options: %+v", in.Options)
	}
}

func TestContract_NullSubObjectsDecodeToNil(t *testing.T) {
	var in ScrapeInput
	if err := json.Unmarshal(readFixture(t, "scrape_input_minimal"), &in); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	if in.Credentials != nil || in.Options != nil {
		t.Errorf("null sub-objects must decode to nil: %+v", in)
	}
}

func TestContract_GoScrapeOutputFixture(t *testing.T) {
	// What the http-worker returns: it never sets warnings or screenshots.
	out := ScrapeOutput{
		Result:      StoredObject{Path: "scrapeflow-results/history/3f8b7a12-0c44-4e7a-9a1e-1b2c3d4e5f60/scrape.md", Size: 5120},
		ContentHash: "00c0ffee12345678",
	}
	got, err := json.MarshalIndent(out, "", "  ")
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	got = append(got, '\n')

	path := filepath.Join(fixtureDir, "go_scrape_output.json")
	if os.Getenv("UPDATE_CONTRACT_FIXTURES") == "1" {
		if err := os.WriteFile(path, got, 0o644); err != nil {
			t.Fatalf("writing fixture: %v", err)
		}
	}
	want := readFixture(t, "go_scrape_output")
	if !bytes.Equal(got, want) {
		t.Fatalf("go_scrape_output.json is stale — regenerate with UPDATE_CONTRACT_FIXTURES=1 go test -count=1\ngot:\n%s", got)
	}
}
