"""migration_3_1_add_respect_robots_to_jobs

Revision ID: 1accea159261
Revises: 34b608ca02ef
Create Date: 2026-04-16 09:43:51.535130

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1accea159261"
down_revision: str | Sequence[str] | None = "34b608ca02ef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jobs", sa.Column("respect_robots", sa.Boolean(), server_default="false", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "respect_robots")
    # ### end Alembic commands ###
