"""add_phase2_fields_to_jobs

Revision ID: 4b7de19105ce
Revises: 5ea37260383e
Create Date: 2026-04-03 09:21:55.694203

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4b7de19105ce"
down_revision: str | Sequence[str] | None = "5ea37260383e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jobs", sa.Column("engine", sa.VARCHAR(length=20), server_default="http", nullable=False)
    )
    op.add_column("jobs", sa.Column("schedule_cron", sa.String(), nullable=True))
    op.add_column("jobs", sa.Column("schedule_status", sa.String(), nullable=True))
    op.add_column("jobs", sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("jobs", sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("jobs", sa.Column("webhook_url", sa.String(), nullable=True))
    op.add_column("jobs", sa.Column("webhook_secret", sa.String(), nullable=True))
    op.add_column(
        "jobs", sa.Column("llm_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.add_column(
        "jobs",
        sa.Column("playwright_options", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###
    # manually added
    # create partial index on next_run_at for active scheduled jobs to optimize scheduler queries
    op.create_index(
        "idx_jobs_next_run_at",
        "jobs",
        ["next_run_at"],
        postgresql_where=sa.text("schedule_cron IS NOT NULL AND schedule_status = 'active'"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "playwright_options")
    op.drop_column("jobs", "llm_config")
    op.drop_column("jobs", "webhook_secret")
    op.drop_column("jobs", "webhook_url")
    op.drop_column("jobs", "last_run_at")
    op.drop_column("jobs", "next_run_at")
    op.drop_column("jobs", "schedule_status")
    op.drop_column("jobs", "schedule_cron")
    op.drop_column("jobs", "engine")
    # ### end Alembic commands ###
