"""migration_3_15_webhook_deliveries_crawl

Revision ID: 4facbc8484ab
Revises: d3558e210813
Create Date: 2026-04-26 07:35:55.356790

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4facbc8484ab"
down_revision: str | Sequence[str] | None = "d3558e210813"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("webhook_deliveries", sa.Column("crawl_id", sa.Uuid(), nullable=True))
    op.alter_column("webhook_deliveries", "run_id", existing_type=sa.UUID(), nullable=True)
    op.create_index(
        op.f("ix_webhook_deliveries_crawl_id"), "webhook_deliveries", ["crawl_id"], unique=False
    )
    op.create_foreign_key(
        "fk_webhook_deliveries_crawl_id",
        "webhook_deliveries",
        "crawls",
        ["crawl_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("ck_webhook_deliveries_job_or_batch", "webhook_deliveries", type_="check")
    op.create_check_constraint(
        "ck_webhook_deliveries_job_or_batch_or_crawls",
        "webhook_deliveries",
        "num_nonnulls(job_id, batch_id, crawl_id) = 1",
    )
    op.create_check_constraint(
        "ck_webhook_deliveries_run_or_crawl",
        "webhook_deliveries",
        "num_nonnulls(run_id, crawl_id) = 1",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_webhook_deliveries_run_or_crawl", "webhook_deliveries", type_="check")
    op.drop_constraint(
        "ck_webhook_deliveries_job_or_batch_or_crawls", "webhook_deliveries", type_="check"
    )
    op.create_check_constraint(
        "ck_webhook_deliveries_job_or_batch",
        "webhook_deliveries",
        "num_nonnulls(job_id, batch_id) = 1",
    )
    op.drop_constraint("fk_webhook_deliveries_crawl_id", "webhook_deliveries", type_="foreignkey")
    op.drop_index(op.f("ix_webhook_deliveries_crawl_id"), table_name="webhook_deliveries")
    op.alter_column("webhook_deliveries", "run_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("webhook_deliveries", "crawl_id")
    # ### end Alembic commands ###
