"""migration_3_3_actions_webhook_url_webhook_events

Revision ID: 53a03ff4c7a1
Revises: cdf971b6d3aa
Create Date: 2026-04-16 18:03:21.218279

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "53a03ff4c7a1"
down_revision: str | Sequence[str] | None = "cdf971b6d3aa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("jobs", sa.Column("webhook_events", sa.ARRAY(sa.Text()), nullable=True))
    op.add_column(
        "jobs",
        sa.Column("playwright_actions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.alter_column(
        "jobs", "webhook_url", existing_type=sa.VARCHAR(), type_=sa.Text(), existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "jobs", "webhook_url", existing_type=sa.Text(), type_=sa.VARCHAR(), existing_nullable=True
    )
    op.drop_column("jobs", "playwright_actions")
    op.drop_column("jobs", "webhook_events")
    # ### end Alembic commands ###
