"""add_is_admin_to_user

Revision ID: 5ea37260383e
Revises: 8a673d38fe23
Create Date: 2026-04-03 08:13:02.348386

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "5ea37260383e"
down_revision: str | Sequence[str] | None = "8a673d38fe23"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
