"""migration_3_7_crawls_crawl_pages_crawl_queue

Revision ID: 62f88e93ca14
Revises: 97555982a68c
Create Date: 2026-04-17 15:46:26.694113

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "62f88e93ca14"
down_revision: str | Sequence[str] | None = "97555982a68c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crawls",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("seed_url", sa.Text(), nullable=False),
        sa.Column("status", sa.VARCHAR(length=20), server_default="queued", nullable=False),
        sa.Column("max_depth", sa.Integer(), server_default="3", nullable=False),
        sa.Column("max_pages", sa.Integer(), server_default="100", nullable=False),
        sa.Column("include_paths", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("exclude_paths", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("ignore_sitemap", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "output_format", sa.VARCHAR(length=20), server_default="markdown", nullable=False
        ),
        sa.Column("engine", sa.VARCHAR(length=20), server_default="http", nullable=False),
        sa.Column("webhook_url", sa.Text(), nullable=True),
        sa.Column("respect_robots", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("schedule_cron", sa.Text(), nullable=True),
        sa.Column("total_queued", sa.Integer(), server_default="0", nullable=False),
        sa.Column("total_completed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("total_failed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_crawls_user_id"), "crawls", ["user_id"], unique=False)
    op.create_table(
        "crawl_pages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("crawl_id", sa.Uuid(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("status", sa.VARCHAR(length=20), server_default="pending", nullable=False),
        sa.Column("result_path", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["crawl_id"], ["crawls.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_crawl_pages_crawl_id", "crawl_pages", ["crawl_id", "status"], unique=False)
    op.create_table(
        "crawl_queue",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("crawl_id", sa.Uuid(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("status", sa.VARCHAR(length=20), server_default="pending", nullable=False),
        sa.Column("crawl_page_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["crawl_id"], ["crawls.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["crawl_page_id"],
            ["crawl_pages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_crawl_queue_pending",
        "crawl_queue",
        ["crawl_id", "created_at"],
        unique=False,
        postgresql_where="status = 'pending'",
    )
    op.create_index("idx_crawl_queue_url", "crawl_queue", ["crawl_id", "url"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_crawl_queue_url", table_name="crawl_queue")
    op.drop_index(
        "idx_crawl_queue_pending", table_name="crawl_queue", postgresql_where="status = 'pending'"
    )
    op.drop_table("crawl_queue")
    op.drop_index("idx_crawl_pages_crawl_id", table_name="crawl_pages")
    op.drop_table("crawl_pages")
    op.drop_index(op.f("ix_crawls_user_id"), table_name="crawls")
    op.drop_table("crawls")
    # ### end Alembic commands ###
