"""add_nats_stream_seq_to_job_runs

Revision ID: 655b7e9b461b
Revises: 669e6fbf05b9
Create Date: 2026-04-03 18:23:53.149323

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "655b7e9b461b"
down_revision: str | Sequence[str] | None = "669e6fbf05b9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("job_runs", sa.Column("nats_stream_seq", sa.BigInteger(), nullable=True))
    # sparse index — only on rows where nats_stream_seq is set; most rows are NULL
    op.create_index(
        "idx_job_runs_nats_stream_seq",
        "job_runs",
        ["nats_stream_seq"],
        postgresql_where=sa.text("nats_stream_seq IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("DROP INDEX IF EXISTS idx_job_runs_nats_stream_seq"))
    op.drop_column("job_runs", "nats_stream_seq")
    # ### end Alembic commands ###
