"""migration_3_4_job_secrets

Revision ID: 6d05497e7c9a
Revises: 53a03ff4c7a1
Create Date: 2026-04-16 18:47:23.946479

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6d05497e7c9a"
down_revision: str | Sequence[str] | None = "53a03ff4c7a1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_secrets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column(
            "secret_type", sa.Enum("proxy", "cookies", name="job_secret_type"), nullable=False
        ),
        sa.Column("encrypted_value", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "secret_type", name="uq_job_secrets_job_type"),
    )
    op.create_index(op.f("ix_job_secrets_job_id"), "job_secrets", ["job_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_job_secrets_job_id"), table_name="job_secrets")
    op.drop_table("job_secrets")
    op.execute(sa.text("DROP TYPE IF EXISTS job_secret_type"))
    # ### end Alembic commands ###
