"""migration_3_5_batches_batch_items

Revision ID: 8d05cd602f03
Revises: 6d05497e7c9a
Create Date: 2026-04-17 09:29:02.387773

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d05cd602f03"
down_revision: str | Sequence[str] | None = "6d05497e7c9a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "batches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.VARCHAR(length=20), server_default="queued", nullable=False),
        sa.Column(
            "output_format", sa.VARCHAR(length=20), server_default="markdown", nullable=False
        ),
        sa.Column("engine", sa.VARCHAR(length=20), server_default="http", nullable=False),
        sa.Column("webhook_url", sa.Text(), nullable=True),
        sa.Column("respect_robots", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("total", sa.Integer(), server_default="0", nullable=False),
        sa.Column("completed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("failed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_batches_user_id"), "batches", ["user_id"], unique=False)
    op.create_table(
        "batch_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("status", sa.VARCHAR(length=20), server_default="pending", nullable=False),
        sa.Column("result_path", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["batch_id"], ["batches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_batch_items_batch_id", "batch_items", ["batch_id", "status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_batch_items_batch_id", table_name="batch_items")
    op.drop_table("batch_items")
    op.drop_index(op.f("ix_batches_user_id"), table_name="batches")
    op.drop_table("batches")
    # ### end Alembic commands ###
