"""migration_3_6_job_runs_batch_nullable

Revision ID: 97555982a68c
Revises: 8d05cd602f03
Create Date: 2026-04-17 09:51:40.717949

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "97555982a68c"
down_revision: str | Sequence[str] | None = "8d05cd602f03"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("job_runs", sa.Column("batch_item_id", sa.Uuid(), nullable=True))
    op.add_column("job_runs", sa.Column("content_hash", sa.VARCHAR(length=16), nullable=True))
    op.alter_column("job_runs", "job_id", existing_type=sa.UUID(), nullable=True)
    op.create_index(
        "idx_job_runs_batch_item_id",
        "job_runs",
        ["batch_item_id"],
        unique=False,
        postgresql_where=sa.text("batch_item_id IS NOT NULL"),
    )
    op.create_foreign_key(
        "fk_job_runs_batch_item_id",
        "job_runs",
        "batch_items",
        ["batch_item_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
    # hand-written: autogenerate skips CHECK constraints
    op.execute(
        sa.text(
            "ALTER TABLE job_runs ADD CONSTRAINT chk_job_runs_single_parent "
            "CHECK ((job_id IS NOT NULL) != (batch_item_id IS NOT NULL))"
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(sa.text("ALTER TABLE job_runs DROP CONSTRAINT IF EXISTS chk_job_runs_single_parent"))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_job_runs_batch_item_id", "job_runs", type_="foreignkey")
    op.drop_index(
        "idx_job_runs_batch_item_id",
        table_name="job_runs",
        postgresql_where=sa.text("batch_item_id IS NOT NULL"),
    )
    op.alter_column("job_runs", "job_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("job_runs", "content_hash")
    op.drop_column("job_runs", "batch_item_id")
    # ### end Alembic commands ###
