"""migration_3_11_job_runs_warnings

Revision ID: 9ba4ee922831
Revises: f050c65b689a
Create Date: 2026-04-22 04:30:40.631836

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9ba4ee922831"
down_revision: str | Sequence[str] | None = "f050c65b689a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "job_runs", sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job_runs", "warnings")
    # ### end Alembic commands ###
