"""migration_3_12_webhook_deliveries_batch

Revision ID: aec9df808334
Revises: 9ba4ee922831
Create Date: 2026-04-24 11:50:12.815423

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aec9df808334"
down_revision: str | Sequence[str] | None = "9ba4ee922831"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("webhook_deliveries", sa.Column("batch_id", sa.Uuid(), nullable=True))
    op.alter_column("webhook_deliveries", "job_id", existing_type=sa.UUID(), nullable=True)
    op.create_index(
        op.f("ix_webhook_deliveries_batch_id"), "webhook_deliveries", ["batch_id"], unique=False
    )
    op.create_foreign_key(
        "fk_webhook_deliveries_batch_id",
        "webhook_deliveries",
        "batches",
        ["batch_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_check_constraint(
        "ck_webhook_deliveries_job_or_batch",
        "webhook_deliveries",
        "num_nonnulls(job_id, batch_id) = 1",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_webhook_deliveries_job_or_batch", "webhook_deliveries", type_="check")
    op.drop_constraint("fk_webhook_deliveries_batch_id", "webhook_deliveries", type_="foreignkey")
    op.drop_index(op.f("ix_webhook_deliveries_batch_id"), table_name="webhook_deliveries")
    op.alter_column("webhook_deliveries", "job_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("webhook_deliveries", "batch_id")
    # ### end Alembic commands ###
