"""migration_3_8_user_quotas

Revision ID: c26955897e1d
Revises: 62f88e93ca14
Create Date: 2026-04-17 15:53:51.265274

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c26955897e1d"
down_revision: str | Sequence[str] | None = "62f88e93ca14"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_quotas",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("monthly_runs_limit", sa.Integer(), nullable=True),
        sa.Column("concurrent_jobs_limit", sa.Integer(), nullable=True),
        sa.Column("storage_bytes_limit", sa.BigInteger(), nullable=True),
        sa.Column("storage_bytes_used", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_quotas")
    # ### end Alembic commands ###
