"""migration_3_2_add_proxy_provider_to_jobs

Revision ID: cdf971b6d3aa
Revises: 1accea159261
Create Date: 2026-04-16 09:49:29.040762

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cdf971b6d3aa"
down_revision: str | Sequence[str] | None = "1accea159261"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("jobs", sa.Column("proxy_provider", sa.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "proxy_provider")
    # ### end Alembic commands ###
