"""migration_3_14_batch_llm_config

Revision ID: d3558e210813
Revises: dc47a96f0eaa
Create Date: 2026-04-25 09:24:56.537490

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d3558e210813"
down_revision: str | Sequence[str] | None = "dc47a96f0eaa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "batches", sa.Column("llm_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("batches", "llm_config")
    # ### end Alembic commands ###
