"""migration_3_13_batch_webhook_secret

Revision ID: dc47a96f0eaa
Revises: aec9df808334
Create Date: 2026-04-25 08:24:53.773541

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc47a96f0eaa"
down_revision: str | Sequence[str] | None = "aec9df808334"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("batches", sa.Column("webhook_secret", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("batches", "webhook_secret")
    # ### end Alembic commands ###
