"""create job runs

Revision ID: e7b433459627
Revises: 4b7de19105ce
Create Date: 2026-04-03 10:04:16.280299

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e7b433459627"
down_revision: str | Sequence[str] | None = "4b7de19105ce"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.VARCHAR(length=20), nullable=False),
        sa.Column("result_path", sa.Text(), nullable=True),
        sa.Column("diff_detected", sa.Boolean(), nullable=True),
        sa.Column("diff_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_runs_created_at"), "job_runs", ["created_at"], unique=False)
    op.create_index(op.f("ix_job_runs_job_id"), "job_runs", ["job_id"], unique=False)
    op.create_index(op.f("ix_job_runs_status"), "job_runs", ["status"], unique=False)
    # ### end Alembic commands ###

    # manually added
    # copy existing jobs data from job to job runs
    op.execute("""
        INSERT INTO job_runs (id, job_id, status, result_path, error, completed_at, created_at)
        SELECT gen_random_uuid(), id, status, result_path, error, updated_at, created_at
        FROM jobs WHERE status != 'pending'
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_job_runs_status"), table_name="job_runs")
    op.drop_index(op.f("ix_job_runs_job_id"), table_name="job_runs")
    op.drop_index(op.f("ix_job_runs_created_at"), table_name="job_runs")
    op.drop_table("job_runs")
    # ### end Alembic commands ###
