"""migration_3_10_api_keys_user_name_unique

Revision ID: f050c65b689a
Revises: ebbcc72c1472
Create Date: 2026-04-17 16:06:33.982721

"""

from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f050c65b689a"
down_revision: str | Sequence[str] | None = "ebbcc72c1472"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_api_keys_user_name", "api_keys", ["user_id", "name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_api_keys_user_name", "api_keys", type_="unique")
    # ### end Alembic commands ###
